[package]
name = "acpi"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
interface = { path = "../interface" }
common = { path = "../../crates/common" }
log = { workspace = true }
