[package]
name = "memory"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
common = { path = "../common" }
bitflags = { workspace = true }
log = { workspace = true }
